# Generated by Django 4.2 on 2023-06-25 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('rules', models.CharField(max_length=250, verbose_name='rules')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'Error',
                'verbose_name_plural': 'Error',
            },
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Language')),
                ('flag', models.CharField(max_length=100, verbose_name='Flag')),
                ('icon', models.CharField(default=0, max_length=5, verbose_name='icon')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='id telegram')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='t_bot.admin_rule', verbose_name='Admin')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='t_bot.lang', verbose_name='Lang')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.PositiveIntegerField(verbose_name='id message')),
                ('message_text', models.TextField(verbose_name='text')),
                ('options', models.TextField(verbose_name='Option')),
                ('created_at', models.DateTimeField(verbose_name='Data')),
                ('status', models.PositiveIntegerField(verbose_name='Status')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='t_bot.user', verbose_name='Profile')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
